More examples
lochyj/UNLE pull request #17
Opened 2023-06-12 06:28 UTC by rotaryViper

2023-06-13 01:17 UTC, lochyj commented
1: this doesn't align with the Github pages build and as such will not be displayed on the site,
2: there is an issue with the first example where it just explodes and
3: it doesn't integrate with the docs which are at unle.js.org, which would benefit with these examples

2023-06-20 07:22 UTC, lochyj requested changes
Possibly make const K a value in a constants.js file to avoid issues when changing the value in the future?

2023-06-20 07:37 UTC, rotaryViper commented
Sure I'll do that.
I'll also implement mobile zooming.

On Tue, 20 June 2023, 17:22 Lachlan Jowett, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Possibly make const K a value in a constants.js file to avoid issues when
> changing the value in the future?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lochyj/UNLE/pull/17#pullrequestreview-1487482334>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWIYOVFMGARSHZ4UQPDW7NLXMFFU7ANCNFSM6AAAAAAZC4RF5A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-20 12:04 UTC, lochyj approved these changes

2023-06-20 12:05 UTC, merged